<a href="https://colab.research.google.com/github/bekhmirzayev/translaterinpython/blob/main/ikkinchi_dars.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Science va Sun'iy intellekt kursi
Ma'lumotlar tahlili(Numpy kutubxonasi)

Numpy kutubxonasini chaqirib olish


In [2]:
import numpy as np

Python list bilan Numpy kutubxonasidagi massivlar(arraylar) hisoblashlari orasidagi farqni ko'ramiz.


In [ ]:
my_list = list(range(100000)) #python list #normal

In [ ]:
my_array = np.array(range(10000))  #numpy array(massivlar)  #vektor

In [ ]:
%time for _ in range(10):[x*2 for x in my_list]  # normal hisoblash 71.1 ms vaqt ketdi

CPU times: user 62.3 ms, sys: 6.76 ms, total: 69.1 ms
Wall time: 71.1 ms


In [ ]:
%time for _ in range(10): my_array*2  # vektorlashgan hisoblash 1.47 ms vaqt ketdi

CPU times: user 1.42 ms, sys: 0 ns, total: 1.42 ms
Wall time: 1.47 ms


In [ ]:
data1 = [4, 6.6, 9, 10, 2]
arr1 = np.array(data1)

data1
arr1

array([ 4. ,  6.6,  9. , 10. ,  2. ])

In [ ]:
data2 = (34, 34, 5,12.9, 89)
arr2 = np.array(data2)

arr2


array([34. , 34. ,  5. , 12.9, 89. ])

In [ ]:
arr2.ndim

1

In [ ]:
data3 = [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]
arr3 = np.array(data3)

In [ ]:
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
arr3.shape

(2, 2, 3)

In [ ]:
arr3.size

12

N olchovli massivni yaratishning boshqa usullari

In [ ]:
arr4=np.zeros((2, 4))  # barcha elementlari 0 ga teng massivni yaratish
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr5 = np.ones((2, 4))  # barcha elementlari 1 ga teng massiv

In [ ]:
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr6 = np.arange(4,20,2)   # 4 dan 20 gacha sonlarni 2 qadamdan chop qilib beruvchi
arr6

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr7=np.arange(20)  # 0 dan 20 gacha 1 qadamlik massiv qilib beradi
arr7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr8=np.asarray(data3)
arr8

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [3]:
arr1 = np.array([1, 2, 3], dtype=np.float64) # bu float64 ma'lumotlar turiga ega massiv
arr1

array([1., 2., 3.])

In [4]:
arr2 = np.array([1, 2, 3], dtype=np.int32) # bu int32 ma'lumotlar turiga ega massiv
arr2

array([1, 2, 3], dtype=int32)

In [5]:
arr1.dtype
arr2.dtype

dtype('int32')

In [6]:
arr = np.array([1, 2, 3, 4]) # int64
arr

array([1, 2, 3, 4])

In [7]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [12]:
data = np.array([3.4, 5.9, 5, 12.3])

In [9]:
data

array([ 3.4,  5.6,  5. , 12.3])

In [14]:
int_data = data.astype(np.int64)
int_data.dtype

dtype('int64')